name: Common Update Template

on:
  workflow_call:
    inputs:
      run_command:
        required: true
        type: string
      commit_message:
        required: true
        type: string

jobs:
  common-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      UV_INDEX_URL: https://pypi.org/simple/

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v5
        with:
          ref: main
          fetch-depth: 1

      - name: Clone crawler project
        run: git clone https://github.com/ci-ke/ProjectSekai-BangDream-story-crawler.git crawler

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Execute command
        working-directory: ./crawler
        run: ${{ inputs.run_command }}

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "${{ inputs.commit_message }}" || echo "No changes to commit"
          git push